config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  resources :foods
  resources :snacks

  devise_scope :user do
    # Redirests signing out users back to sign-in
    get "/login", to: "devise/sessions#new"

    # Destroy Session
    get '/logout', to: 'devise/sessions#destroy'

    root 'dashboard#index'  
  end  
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/food.rb
class Food < ApplicationRecord
  belongs_to :user
end

app/models/snack.rb
class Snack < ApplicationRecord
  has_many :foods
  belongs_to :user

end

app/models/taco_service.rb
class TacoService
  include HTTParty
    base_uri 'https://taco.brunonascimento.dev.br/api/v1'
  

  def self.category
    get('/category')
  end

  def self.foods
    get('/food')
  end

  def self.id(taco_id)
    get("/food/#{taco_id}")
  end
  
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
  
  has_one_attached :avatar
  
  ## Validations
  validates :avatar, file_size: { less_than_or_equal_to: 5.megabytes },
  file_content_type: { allow: ['image/jpeg', 'image/png', 'image/gif'] }
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  before_action :configure_permitted_parameters, if: :devise_controller?
  protected
     def configure_permitted_parameters
        devise_parameter_sanitizer.permit(:sign_up) { |u| u.permit(:email, :password)}
        devise_parameter_sanitizer.permit(:account_update) { |u| u.permit(:avatar, :email, :password, :current_password)}
     end
end

app/controllers/dashboard_controller.rb
class DashboardController < ApplicationController
  before_action :authenticate_user!
  
  def index
  end
end

app/controllers/food_controller.rb
class FoodController < ApplicationController
  before_action :set_taco_service

  def index
    @foods = @taco_service.get_foods
  end

  def categories
    @categories = @taco_service.get_categories
  end

  private
  def set_taco_service
    @taco_service = TacoService.new
  end

end

app/controllers/foods_controller.rb
class FoodsController < ApplicationController
  before_action :set_food, only: %i[ show edit update destroy ]
  before_action :set_current_user

  # GET /foods or /foods.json
  def index
    @foods = Food.all
  end

  # GET /foods/1 or /foods/1.json
  def show
     @food
     @taco_food = TacoService.id(@food.taco_id)
  end

  # GET /foods/new
  def new
    @food = Food.new
    @taco_foods = TacoService.foods.map{ |food| [food['description'], food ['id']] }
  end

  # GET /foods/1/edit
  def edit
  end

  # POST /foods or /foods.json
  def create    
    @food = Food.new(food_params)
    @food.user = current_user

    respond_to do |format|
      if @food.save
        format.html { redirect_to food_url(@food), notice: "Food was successfully created." }
        format.json { render :show, status: :created, location: @food }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @food.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /foods/1 or /foods/1.json
  def updatetaco_id
    respond_to do |format|
      if @food.update(food_params)
        format.html { redirect_to food_url(@food), notice: "Food was successfully updated." }
        format.json { render :show, status: :ok, location: @food }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @food.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /foods/1 or /foods/1.json
  def destroy
    @food.destroy

    respond_to do |format|
      format.html { redirect_to foods_url, notice: "Food was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_food
      @food = Food.find(params[:id])
    end

    def set_current_user
      user_id = current_user.id
    end

    # Only allow a list of trusted parameters through.
    def food_params
      params.require(:food).permit(:taco_id, :user_id, :snack)
    end
end

app/controllers/snacks_controller.rb
class SnacksController < ApplicationController
  before_action :set_snack, only: %i[ show edit update destroy ]
  before_action :set_current_user

  # GET /snacks or /snacks.json
  def index
    @snacks = Snack.all
  end

  # GET /snacks/1 or /snacks/1.json
  def show
    @taco_food = TacoService.id(@food.taco_id)
  end

  # GET /snacks/new
  def new
    @snack = Snack.new
    @taco_foods = TacoService.foods.map{ |food| [food['description'], food ['id']] }
  end

  # GET /snacks/1/edit
  def edit
  end

  # POST /snacks or /snacks.json
  def create
    @snack = Snack.new(snack_params)
    @snack.user = current_user

    respond_to do |format|
      if @snack.save
        format.html { redirect_to snack_url(@snack), notice: "Snack was successfully created." }
        format.json { render :show, status: :created, location: @snack }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @snack.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /snacks/1 or /snacks/1.json
  def update
    respond_to do |format|
      if @snack.update(snack_params)
        format.html { redirect_to snack_url(@snack), notice: "Snack was successfully updated." }
        format.json { render :show, status: :ok, location: @snack }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @snack.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /snacks/1 or /snacks/1.json
  def destroy
    @snack.destroy

    respond_to do |format|
      format.html { redirect_to snacks_url, notice: "Snack was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_snack
      @snack = Snack.find(params[:id])
    end

    def set_current_user
      user_id = current_user.id
    end

    # Only allow a list of trusted parameters through.
    def snack_params
      params.require(:snack).permit(:title, :food_id, :taco_id, :user_id)
    end
end

app/controllers/turbo_devise_controller.rb
class TurboDeviseController < ApplicationController
  class Responder < ActionController::Responder
    def to_turbo_stream
      controller.render(options.merge(formats: :html))
    rescue ActionView::MissingTemplate => error
      if get?
        raise error
      elsif has_errors? && default_action
        render rendering_options.merge(formats: :html, status: :unprocessable_entity)
      else
        redirect_to navigation_location
      end
    end
  end

  self.responder = Responder
  respond_to :html, :turbo_stream
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
end

app/helpers/application_helper.rb
module ApplicationHelper
  def tailwind_classes_for(flash_type)
    {
      notice: "bg-green-400 border-l-4 border-green-700 text-white",
      error:   "bg-red-400 border-l-4 border-red-700 text-black",
    }.stringify_keys[flash_type.to_s] || flash_type.to_s
  end
end

app/helpers/food_helper.rb
module FoodHelper
end

app/helpers/foods_helper.rb
module FoodsHelper
end

app/helpers/snacks_helper.rb
module SnacksHelper
end

app/views/dashboard/index.html.erb
<div class="min-h-full">
  <%= render "helpers/navbar" %>
  <main>
    <div class="max-w-7xl mx-auto px-4 sm:px-6 lg:px-8">
      <!-- Replace with your content -->
      <%= render "helpers/charts" %>
      <!-- /End replace -->
    </div>
  </main>
</div>

app/views/food/categories.html.erb
<div class="min-h-full">
  <%= render "helpers/navbar" %>
  <main>
    <div class="max-w-7xl mx-auto py-6 sm:px-6 lg:px-8">
      <table>
        <thead>
          <td>ID</td>
          <td>Description</td>
        </thead>
        <% @categories.each do |c| %>
        <tbody>
          <td><%= c['id'] %></td>
          <td><%= c['category'] %></td>
        </tbody>
        <% end %>
      </table>
    </div>
  </main>
</div>

app/views/food/index.html.erb
<%= render "helpers/navbar" %>

  <div class="pt-5 max-w-7xl mx-auto px-4 sm:px-6 lg:px-8">
    <table class="table-fixed">
      <thead class="border-b bg-blue-500 text-white px-3 py-2 ">
        <tr class="border-collapse border border-slate-400">
          <th scope="col" class="text-sm font-medium text-white px-6 py-4">ID</th>
          <th scope="col" class="text-sm font-medium text-white px-6 py-4">Descrição</th>
          <th scope="col" class="text-sm font-medium text-white px-6 py-4">Proteína (g)</th>
          <th scope="col" class="text-sm font-medium text-white px-6 py-4">Carboidrato (g) </th>
          <th scope="col" class="text-sm font-medium text-white px-6 py-4">Calorias (cal) </th>
        </tr>
      </thead>
      <% @foods.each do |food| %>
        <tbody>
          <tr class="border-b">
            <td class="text-sm text-gray-900 font-light px-6 py-4">
              <%= food['id'] %>
            </td>
            <td class="text-sm text-gray-900 font-light px-6 py-4">
              <%= food['description'] %>
            </td>
            <td class="text-sm text-gray-900 font-light px-6 py-4">
              <%= food['attributes']['protein']['qty'].to_f.round(2) rescue '0' %>
            </td>
            <td class="text-sm text-gray-900 font-light px-6 py-4">
              <%= food['attributes']['carbohydrate']['qty'].to_f.round(2) rescue '0' %>
            </td>
            <td class="text-sm text-gray-900 font-light px-6 py-4">
              <%= food['attributes']['energy']['kcal'].to_i.round() %>
            </td>
          </tr>
        </tbody>
        <% end %>
    </table>
  </div>
  </div>

app/views/foods/_food.html.erb
<div id="<%= dom_id food %>">
  <p class="my-5">
    <strong class="block font-medium mb-1">Taco:</strong>
    <%= food.taco_id %>
  </p>

  <% if action_name != "show" %>
    <%= link_to "Show this food", food, class: "ml-2 rounded-lg py-3 px-5 bg-gray-500 inline-block font-medium  text-white" %>
    
    <hr class="mt-6">
  <% end %>
</div>

app/views/foods/_form.html.erb
<%= form_with(model: food, class: "contents") do |form| %>
  <% if food.errors.any? %>
    <div id="error_explanation" class="bg-red-50 text-red-500 px-3 py-2 font-medium rounded-lg mt-3">
      <h2><%= pluralize(food.errors.count, "error") %> prohibited this food from being saved:</h2>

      <ul>
        <% food.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="my-5">
    <%= form.label :snack %>
    <%= form.text_field :snack, class: "block shadow rounded-md border border-gray-200 outline-none px-3 py-2 mt-2 w-full" %>
  </div>

  <div class="my-5">
    <%= form.label :taco_id %>
    <%= form.select :taco_id, @taco_foods, {}, { class: "block shadow rounded-md border border-gray-200 outline-none px-3 py-2 mt-2 w-full" }  %>
  </div>

  <div class="inline">
    <%= form.submit class: "rounded-lg py-3 px-5 bg-blue-600 text-white inline-block font-medium cursor-pointer" %>
  </div>
<% end %>

app/views/foods/edit.html.erb
<div class="mx-auto md:w-2/3 w-full">
  <h1 class="font-bold text-4xl">Editing food</h1>

  <%= render "form", food: @food %>

  <%= link_to "Show this food", @food, class: "ml-2 rounded-lg py-3 px-5 bg-gray-100 inline-block font-medium" %>
  <%= link_to "Back to foods", foods_path, class: "ml-2 rounded-lg py-3 px-5 bg-gray-100 inline-block font-medium" %>
</div>

app/views/foods/index.html.erb
<%= render "helpers/navbar" %>

  <div class="pt-5 mx-auto md:w-2/3 w-full">

    <div class="w-full">
      <% if notice.present? %>
        <p class="py-2 px-3 bg-green-50 mb-5 text-green-500 font-medium rounded-lg inline-block" id="notice">
          <%= notice %>
        </p>
        <% end %>

          <div class="flex justify-between items-center">
            <h1 class="font-bold text-4xl">Foods</h1>
            <%= link_to 'New food' , new_food_path,
              class: "rounded-lg py-3 px-5 bg-blue-600 text-white block font-medium" %>
          </div>

          <div id="foods" class="min-w-full">
            <%= render @foods %>
            
          </div>
    </div>

  </div>

app/views/foods/new.html.erb
<%= render "helpers/navbar" %>

<div class="pt-5 mx-auto md:w-2/3 w-full">
  <h1 class="font-bold text-4xl">New food</h1>

  <%= render "form", food: @food %>

  <%= link_to 'Back to foods', foods_path, class: "ml-2 rounded-lg py-3 px-5 bg-gray-100 inline-block font-medium" %>
</div>

app/views/foods/show.html.erb
<%= render "helpers/navbar" %>

  <div class="pt-5 mx-auto md:w-2/3 w-full">
    
  <div class="mx-auto">
    <% if notice.present? %>
      <p class="py-2 px-3 bg-green-50 mb-5 text-green-500 font-medium rounded-lg inline-block" id="notice"><%= notice %></p>
    <% end %>
    
    <h1 class="text-4xl font-extrabold dark:text-white"><%= @food.snack %></h1>
    <h6 class="text-lg font-bold dark:text-white"><%= Time.at(@food.created_at.to_i/1000).strftime('%d/%m/%Y %H:%M') %></h6>

    <div class="pt-5 max-w-7xl mx-auto px-4 sm:px-6 lg:px-8">
      <table class="table-fixed">
        <thead class="border-b bg-blue-500 text-white px-3 py-2 ">
          <tr class="border-collapse border border-slate-400">
            <th scope="col" class="text-sm font-medium text-white px-6 py-4">ID</th>
            <th scope="col" class="text-sm font-medium text-white px-6 py-4">Descrição</th>
            <th scope="col" class="text-sm font-medium text-white px-6 py-4">Proteína (g)</th>
            <th scope="col" class="text-sm font-medium text-white px-6 py-4">Carboidrato (g) </th>
            <th scope="col" class="text-sm font-medium text-white px-6 py-4">Calorias (cal) </th>
          </tr>
        </thead>
        <% @taco_food.each do |taco_food| %>
          <tbody>
            <tr class="border-b">
              <td class="text-sm text-gray-900 font-light px-6 py-4">
                <%= taco_food['id'] %>
              </td>
              <td class="text-sm text-gray-900 font-light px-6 py-4">
                <%= taco_food['description'] %>
              </td>
              <td class="text-sm text-gray-900 font-light px-6 py-4">
                <%= taco_food['attributes']['protein']['qty'].to_f.round(2) rescue '0' %>
              </td>
              <td class="text-sm text-gray-900 font-light px-6 py-4">
                <%= taco_food['attributes']['carbohydrate']['qty'].to_f.round(2) rescue '0' %>
              </td>
              <td class="text-sm text-gray-900 font-light px-6 py-4">
                <%= taco_food['attributes']['energy']['kcal'].to_i.round() %>
              </td>
            </tr>
          </tbody>
          <% end %>
      </table>
  
    
    <div class="inline-block ml-2">
      <%= button_to 'Destroy this food', food_path(@food), method: :delete, class: "mt-2 rounded-lg py-3 px-5 bg-red-500 font-medium text-white" %>
    </div>
    <%= link_to 'Back to foods', foods_path, class: "ml-2 rounded-lg py-3 px-5 bg-gray-500 inline-block font-medium  text-white" %>
  </div>
</div>

app/views/helpers/_charts.html.erb
   <div class="px-4 py-6 sm:px-0">
    <div class="border-4 border-dashed border-gray-200 rounded-lg h-96"></div>
  </div>

app/views/helpers/_navbar.html.erb
<div class="max-w-7xl mx-auto px-4 sm:px-6 lg:px-8">
  <div class="flex items-center justify-between h-16">
    <nav class="bg-white px-2 sm:px-4 py-2.5 dark:bg-gray-900 fixed w-full z-20 top-0 left-0 border-b border-gray-200 dark:border-gray-600">
      <div class="container flex flex-wrap items-center justify-between mx-auto">
      <a href="/" class="flex items-center">
          <img src="/meu-rango.svg" width="50" height="50" alt="meu-rango-logo">
          <span class="self-center text-xl font-semibold whitespace-nowrap dark:text-white">Meu Rango</span>
      </a>
      <div class="flex md:order-2">
    
        <div class="hidden md:block">
          <div class="ml-4 flex items-center md:ml-6">
            
            <div class="ml-3 p">
    
              <div class="text-base font-medium leading-none text-white-400">
                <h6> <%= current_user.email%> </h6>
              </div>
              
              <div class="text-sm font-medium leading-none text-white-400">
                <a href="/users/edit"
                class="">
                Minha Conta
              </a>
              </div>  
            </div>
            
            
            <div class="ml-3 relative pr-5 ">
              <div>
                <span type="span"
                  class="max-w-xs bg-gray-800 rounded-full flex items-center text-sm focus:outline-none focus:ring-2 focus:ring-offset-2 focus:ring-offset-gray-800 focus:ring-white"
                  id="user-menu-button" aria-expanded="false" aria-haspopup="true">
                  <img class="h-8 w-8 rounded-full" <% if current_user.avatar.present? %>
                  <%= image_tag(current_user.avatar.variant(resize_to_fill: [80, 80]), class: "rounded-circle" ) %>
                    <% else %>
                      <img alt="image" class="rounded-circle" src="/default_avatar.jpg">
                      <% end %>
    
                </span>
              </div>
    
            </div>
          </div>
          <div class="-mr-2 flex md:hidden">
            <!-- Mobile menu button -->
            <button type="button"
              class="bg-gray-800 inline-flex items-center justify-center p-2 rounded-md text-gray-400 hover:text-white hover:bg-gray-700 focus:outline-none focus:ring-2 focus:ring-offset-2 focus:ring-offset-gray-800 focus:ring-white"
              aria-controls="mobile-menu" aria-expanded="false">
              <span class="sr-only">Open main menu</span>
    
              <svg class="block h-6 w-6" xmlns="http://www.w3.org/2000/svg" fill="none" viewBox="0 0 24 24"
                stroke-width="2" stroke="currentColor" aria-hidden="true">
                <path stroke-linecap="round" stroke-linejoin="round" d="M4 6h16M4 12h16M4 18h16" />
              </svg>
              <svg class="hidden h-6 w-6" xmlns="http://www.w3.org/2000/svg" fill="none" viewBox="0 0 24 24"
                stroke-width="2" stroke="currentColor" aria-hidden="true">
                <path stroke-linecap="round" stroke-linejoin="round" d="M6 18L18 6M6 6l12 12" />
              </svg>
            </button>
          </div>
        </div>
        
          <a type="button" class="text-white bg-blue-700 hover:bg-blue-800 focus:ring-4 focus:outline-none focus:ring-blue-300 font-medium rounded-lg text-sm px-5 py-2.5 text-center mr-3 md:mr-0 dark:bg-blue-600 dark:hover:bg-blue-700 dark:focus:ring-blue-800" href="/logout"> Logout </a>
       
          
          <button data-collapse-toggle="navbar-sticky" type="button" class="inline-flex items-center p-2 text-sm text-gray-500 rounded-lg md:hidden hover:bg-gray-100 focus:outline-none focus:ring-2 focus:ring-gray-200 dark:text-gray-400 dark:hover:bg-gray-700 dark:focus:ring-gray-600" aria-controls="navbar-sticky" aria-expanded="false">
            <span class="sr-only">Open main menu</span>
            <svg class="w-6 h-6" aria-hidden="true" fill="currentColor" viewBox="0 0 20 20" xmlns="http://www.w3.org/2000/svg"><path fill-rule="evenodd" d="M3 5a1 1 0 011-1h12a1 1 0 110 2H4a1 1 0 01-1-1zM3 10a1 1 0 011-1h12a1 1 0 110 2H4a1 1 0 01-1-1zM3 15a1 1 0 011-1h12a1 1 0 110 2H4a1 1 0 01-1-1z" clip-rule="evenodd"></path></svg>
        </button>
      </div>
      <div class="items-center justify-between hidden w-full md:flex md:w-auto md:order-1" id="navbar-sticky">
        <ul class="flex flex-col p-4 mt-4 border border-gray-100 rounded-lg bg-gray-50 md:flex-row md:space-x-8 md:mt-0 md:text-sm md:font-medium md:border-0 md:bg-white dark:bg-gray-800 md:dark:bg-gray-900 dark:border-gray-700">
          <li>
            <a href="/" class="block py-2 pl-3 pr-4 text-white bg-blue-700 rounded md:bg-transparent md:text-blue-700 md:p-0 dark:text-white" aria-current="page">Dashboard</a>
          </li>
          <li>
            <a href="/foods" class="block py-2 pl-3 pr-4 text-gray-700 rounded hover:bg-gray-100 md:hover:bg-transparent md:hover:text-blue-700 md:p-0 md:dark:hover:text-white dark:text-gray-400 dark:hover:bg-gray-700 dark:hover:text-white md:dark:hover:bg-transparent dark:border-gray-700">Refeições</a>
          </li>
        </ul>
      </div>
      </div>
    </nav>
  </div>  
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>MeuRango</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <%= stylesheet_link_tag "tailwind", "inter-font", "data-turbo-track": "reload" %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
    <%= javascript_include_tag "application", "data-turbo-track": "reload", defer: true %>
  </head>

  <body>
    <main>
      <% if notice %>
        <div class="bg-green-100 rounded-lg py-5 px-6 mb-3 text-base text-green-700 inline-flex items-center w-full" role="alert">
          <svg aria-hidden="true" focusable="false" data-prefix="fas" data-icon="check-circle" class="w-4 h-4 mr-2 fill-current" role="img" xmlns="http://www.w3.org/2000/svg" viewBox="0 0 512 512">
            <path fill="currentColor" d="M504 256c0 136.967-111.033 248-248 248S8 392.967 8 256 119.033 8 256 8s248 111.033 248 248zM227.314 387.314l184-184c6.248-6.248 6.248-16.379 0-22.627l-22.627-22.627c-6.248-6.249-16.379-6.249-22.628 0L216 308.118l-70.059-70.059c-6.248-6.248-16.379-6.248-22.628 0l-22.627 22.627c-6.248 6.248-6.248 16.379 0 22.627l104 104c6.249 6.249 16.379 6.249 22.628.001z"></path>
          </svg>
          <%= notice %>
        </div>
      <% end %>
      
      <% if alert %>
      <div class="bg-red-100 rounded-lg py-5 px-6 mb-3 text-base text-red-700 inline-flex items-center w-full" role="alert">
        <svg aria-hidden="true" focusable="false" data-prefix="fas" data-icon="times-circle" class="w-4 h-4 mr-2 fill-current" role="img" xmlns="http://www.w3.org/2000/svg" viewBox="0 0 512 512">
          <path fill="currentColor" d="M256 8C119 8 8 119 8 256s111 248 248 248 248-111 248-248S393 8 256 8zm121.6 313.1c4.7 4.7 4.7 12.3 0 17L338 377.6c-4.7 4.7-12.3 4.7-17 0L256 312l-65.1 65.6c-4.7 4.7-12.3 4.7-17 0L134.4 338c-4.7-4.7-4.7-12.3 0-17l65.6-65-65.6-65.1c-4.7-4.7-4.7-12.3 0-17l39.6-39.6c4.7-4.7 12.3-4.7 17 0l65 65.7 65.1-65.6c4.7-4.7 12.3-4.7 17 0l39.6 39.6c4.7 4.7 4.7 12.3 0 17L312 256l65.6 65.1z"></path>
        </svg>
        <p><%= alert %></p>
      </div>
      <% end %>
      <%= yield %>
    </main>
  </body>
</html>

app/views/snacks/_form.html.erb
<%= form_with(model: snack, class: "contents") do |form| %>
  <% if snack.errors.any? %>
    <div id="error_explanation" class="bg-red-50 text-red-500 px-3 py-2 font-medium rounded-lg mt-3">
      <h2><%= pluralize(snack.errors.count, "error") %> prohibited this snack from being saved:</h2>

      <ul>
        <% snack.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="my-5">
    <%= form.label :title %>
    <%= form.text_field :title, class: "block shadow rounded-md border border-gray-200 outline-none px-3 py-2 mt-2 w-full" %>
  </div>

  <div class="my-5">
    <%= form.label :taco_id %>
    <%= form.select :taco_id, @taco_foods, {}, { class: "block shadow rounded-md border border-gray-200 outline-none px-3 py-2 mt-2 w-full" }  %>
  </div>

  <div class="inline">
    <%= form.submit class: "rounded-lg py-3 px-5 bg-blue-600 text-white inline-block font-medium cursor-pointer" %>
  </div>
<% end %>

app/views/snacks/_snack.html.erb
<div id="<%= dom_id snack %>">
  <p class="my-5">
    <strong class="block font-medium mb-1">Title:</strong>
    <%= snack.title %>
  </p>

  <p class="my-5">
    <strong class="block font-medium mb-1">Food:</strong>
    <%= snack.food_id %>
  </p>

  <% if action_name != "show" %>
    <%= link_to "Show this snack", snack, class: "rounded-lg py-3 px-5 bg-gray-100 inline-block font-medium" %>
    <%= link_to 'Edit this snack', edit_snack_path(snack), class: "rounded-lg py-3 ml-2 px-5 bg-gray-100 inline-block font-medium" %>
    <hr class="mt-6">
  <% end %>
</div>

app/views/snacks/edit.html.erb
<div class="mx-auto md:w-2/3 w-full">
  <h1 class="font-bold text-4xl">Editing snack</h1>

  <%= render "form", snack: @snack %>

  <%= link_to "Show this snack", @snack, class: "ml-2 rounded-lg py-3 px-5 bg-gray-100 inline-block font-medium" %>
  <%= link_to "Back to snacks", snacks_path, class: "ml-2 rounded-lg py-3 px-5 bg-gray-100 inline-block font-medium" %>
</div>

app/views/snacks/index.html.erb
<%= render "helpers/navbar" %>

<div class="pt-5 mx-auto md:w-2/3 w-full">
  <div class="w-full">
    <% if notice.present? %>
      <p class="py-2 px-3 bg-green-50 mb-5 text-green-500 font-medium rounded-lg inline-block" id="notice"><%= notice %></p>
    <% end %>
  
    <div class="flex justify-between items-center">
      <h1 class="font-bold text-4xl">Snacks</h1>
      <%= link_to 'New snack', new_snack_path, class: "rounded-lg py-3 px-5 bg-blue-600 text-white block font-medium" %>
    </div>
  
    <div id="snacks" class="min-w-full">
      <%= render @snacks %>
    </div>
  </div>
</div>

app/views/snacks/new.html.erb
<%= render "helpers/navbar" %>

<div class="pt-5 mx-auto md:w-2/3 w-full">
  <h1 class="font-bold text-4xl">New snack</h1>

  <%= render "form", snack: @snack %>

  <%= link_to 'Back to snacks', snacks_path, class: "ml-2 rounded-lg py-3 px-5 bg-gray-100 inline-block font-medium" %>
</div>

app/views/snacks/show.html.erb
<div class="mx-auto md:w-2/3 w-full flex">
  <div class="mx-auto">
    <% if notice.present? %>
      <p class="py-2 px-3 bg-green-50 mb-5 text-green-500 font-medium rounded-lg inline-block" id="notice"><%= notice %></p>
    <% end %>

    <%= render @snack %>

    <%= link_to 'Edit this snack', edit_snack_path(@snack), class: "mt-2 rounded-lg py-3 px-5 bg-gray-100 inline-block font-medium" %>
    <div class="inline-block ml-2">
      <%= button_to 'Destroy this snack', snack_path(@snack), method: :delete, class: "mt-2 rounded-lg py-3 px-5 bg-gray-100 font-medium" %>
    </div>
    <%= link_to 'Back to snacks', snacks_path, class: "ml-2 rounded-lg py-3 px-5 bg-gray-100 inline-block font-medium" %>
  </div>
</div>